print("What is your name?")
name = input()
print()
print("What is a good Email to reach you at?")
Emal = input()
print()
print("What company are you with?")
comp = input()
print()
print("What is your access level (e.g Attendee, Staff etc.)?")
rank = input()
print()

print()
print()


print("+----------------------------------------+")
print("| ATTENDEE : " + name.ljust(28) + "|")
print("| CONTACT : " + Emal.ljust(29) + "|")
print("| COMPANY : " + comp.ljust(29) + "|")
print("| RANK : " + rank.ljust(32) + "|")
print("|----------------------------------------|")
print("|              APEX TERMINAL SIGN IN     |")
print("+----------------------------------------+")